import Header from "../components/header/Header";
import type { Metadata } from "next";
import "./globals.css";
import { ReduxProvider } from "../redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body>
          <Header />
          <div className="app-content">{children}</div>
        </body>
      </html>
    </ReduxProvider>
  );
}
